on: [push]

name: Push Quest FE to docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github action'
        uses: actions/checkout@master

      - name: 'Setup Node'
        uses: actions/setup-node@master

      - name: 'Install NPM'
        run: npm install

      - name: 'Build the static files'
        run: npm run build

      - name: 'Generate the docker image from the static files'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: lordrahl/quest-front-end
          tag: latest
